import type { Metadata } from "next";

import { WavyBackground } from "../../components/ui/wavy-background";
import "../globals.css";
import Topbar from "./TopbarAuth";
import { Commissioner } from "next/font/google";


const commissioner = Commissioner({
  subsets: ["latin"],
  variable: "--font-commissioner",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 


{
  return (
    <html lang="mn">
<body className={`${commissioner.variable} antialiased font-sans`}>
        <Topbar/>
        {/* <WavyBackground className="max-w-4xl mx-auto pb-40"> */}
        
  
      
        
        {/* <UserProvider> */}

        {children}
        {/* </WavyBackground> */}
        {/* </UserProvider> */}
      </body>
    </html>
  );
}
